{% set name = "perl-type-tiny" %}
{% set version = "1.016001" %}
{% set sha256 = "d7eb2c85f8829486ce843a4c77a3d53f141b69a755de6f008a22945caf238fba" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/T/TO/TOBYINK/Type-Tiny-1.016001.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-exporter-tiny >=1.000000
    - perl-extutils-makemaker

  run:
    - perl
    - perl-exporter-tiny >=1.000000

test:
  imports:
    - Type::Coercion
    - Type::Coercion::FromMoose
    - Type::Coercion::Union
    - Type::Library
    - Type::Params
    - Type::Parser
    - Type::Registry
    - Type::Tiny
    - Type::Tiny::Class
    - Type::Tiny::Duck
    - Type::Tiny::Enum
    - Type::Tiny::Intersection
    - Type::Tiny::Role
    - Type::Tiny::Union
    - Type::Utils
    - Types::Common::Numeric
    - Types::Common::String
    - Types::Standard
    - Types::Standard::ArrayRef
    - Types::Standard::CycleTuple
    - Types::Standard::Dict
    - Types::Standard::HashRef
    - Types::Standard::Map
    - Types::Standard::ScalarRef
    - Types::Standard::Tuple
    - Types::TypeTiny

about:
  home: https://metacpan.org/release/Type-Tiny
  license: perl_5
  summary: 'tiny, yet Moo(se)-compatible type constraint'
