{% set name = "nanomonsv" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nanomonsv-{{ version }}.tar.gz
  sha256: 846b2bc3fd86dde29e5898dbfe19ed4e94cbf6d800b6a9e3e606bae91d7dc06a

build:
  entry_points:
    - nanomonsv = nanomonsv:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.6,<3.11
    - pip
    - setuptools
    - cython
    - pysam >=0.19.1
    - numpy >=1.23.0
  run:
    - python >=3.6,<3.11
    - htslib >=1.15
    - mafft >=7.407
    - racon >=1.4.3
    - pysam >=0.19.1
    - numpy >=1.23.0
    - parasail-python >=1.2.4
    - minimap2 >=2.24
    - bwa >=0.7.17
    - RepeatMasker >=4.1.1
    - bedtools >=2.30.0
    - cython
test:
  commands:
    - pip check
    - nanomonsv --help
  requires:
    - pip

about:
  home: https://github.com/friend1ws/nanomonsv
  summary: Python tools for detecting structural variation from nanopore sequence data
  license: GPL-3.0
  license_file: LICENSE

extra:
  skip-lints:
    - cython_must_be_in_host
  recipe-maintainers:
    - aokad
