{% set name = "nanomonsv" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nanomonsv-{{ version }}.tar.gz
  sha256: 846b2bc3fd86dde29e5898dbfe19ed4e94cbf6d800b6a9e3e606bae91d7dc06a

build:
  entry_points:
    - nanomonsv = nanomonsv:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python =3.10
    - cython
    - pip
  run:
    - python =3.10
    - htslib
    - mafft
    - racon
    - pysam
    - numpy
    - parasail-python
    - minimap2
    - bwa
    - RepeatMasker
    - bedtools
    
test:
  commands:
    - nanomonsv --help

about:
  home: https://github.com/friend1ws/nanomonsv
  summary: Python tools for detecting structural variation from nanopore sequence data
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aokad
